version: '3'
services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web-app

  web-app:
    build: ./web-app
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"

